# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'

# Add 'AnyChange' label to any changes within the entire repository
AnyChange:
- changed-files:
  - any-glob-to-any-file: '**'
